name: TatumTudor
favicon: null
layout_spectrum: 0.6848
typography_spectrum: 0.59139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130f28'
    - '#094c83'
    - '#e8002f'
    - '#00bbfe'
    - '#02ecf5'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5496852051001042
  rhythmicContrast: 0.5
purpose: []
